GET http://localhost:8080/api/persons

###
POST http://localhost:8080/api/persons HTTP/1.1
Content-Type: application/json

{
  "name": "Zhao ZhiHao",
  "number": "134-0935-5896"
}

###
POST http://localhost:8080/api/persons HTTP/1.1
Content-Type: application/json

{
  "name": "Zhao ZhiHao",
  "number": "134-09355896"
}

###
PUT http://localhost:8080/api/persons/642846278d3068f0f3394138 HTTP/1.1
Content-Type: application/json

{
  "name": "Zhao ZhiHao",
  "number": "134-09355896"
}

###
POST http://localhost:8080/api/persons HTTP/1.1
Content-Type: application/json

{ }

###
POST http://localhost:8080/api/persons HTTP/1.1
Content-Type: application/json

{
  "name": "Zhao ZhiHao"
}

###
POST http://localhost:8080/api/persons HTTP/1.1
Content-Type: application/json

{
  "number": "134-0935-5896"
}

###
GET http://localhost:8080/api/persons/642846278d3068f0f3394138

###
GET http://localhost:8080/api/persons/100

###
DELETE http://localhost:3001/api/persons/1

###
DELETE http://localhost:8080/api/persons/642845ee8d3068f0f3394134